name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # Required for full tag history

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

      - name: Prepare publish folder
        run: |
          mkdir publish
          cp target/release/impulse.exe publish/
          powershell -Command "Copy-Item -Recurse -Force lib publish/lib"

      - name: Zip published output
        run: |
          powershell Compress-Archive -Path "publish/*" -DestinationPath "release.zip"

      - name: Get latest tag and generate next version
        id: get_version
        shell: pwsh
        run: |
          git fetch --tags
          $latestTag = git describe --tags --abbrev=0 --match "v*" 2>$null
          if (-not $latestTag -or $latestTag -eq "") {
            $latestTag = "v1.0.0"
          }
          Write-Host "Latest tag: $latestTag"
          
          $parts = $latestTag.TrimStart("v").Split(".")
          $major = [int]$parts[0]
          $minor = [int]$parts[1]
          $patch = [int]$parts[2] + 1
          $newTag = "v$major.$minor.$patch"
          echo "new_tag=$newTag" >> $env:GITHUB_OUTPUT

          Write-Host "New tag: $newTag"
          echo "new_tag=$newTag" >> $env:GITHUB_OUTPUT


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.new_tag }}
          name: Release ${{ steps.get_version.outputs.new_tag }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Configure Git for push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
